name: Auto Tag Patch

on:
  push:
    branches:
      - txwdzxq-patch-1

jobs:
  auto-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"

    - name: Get latest tag
      id: get_tag
      run: |
        latest_tag=$(git describe --tags --abbrev=0)
        echo "latest_tag=$latest_tag" >> $GITHUB_ENV

    - name: Bump patch version
      id: bump
      run: |
        tag=$latest_tag
        IFS='.' read -r major minor patch <<< "${tag#v}"
        new_patch=$((patch + 1))
        new_tag="v${major}.${minor}.${new_patch}"
        echo "new_tag=$new_tag" >> $GITHUB_ENV

    - name: Create new tag
      run: |
        git tag $new_tag
        git push origin $new_tag
