name: Auto Tag Patch

on:
  push:
    branches:
      - txwdzxq-patch-1

permissions:
  contents: write

jobs:
  auto-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Bump patch
        run: |
          IFS='.' read -r major minor patch <<< "${{ env.latest_tag#v }}"
          new_patch=$((patch + 1))
          new_tag="v${major}.${minor}.${new_patch}"
          echo "new_tag=$new_tag"
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag $new_tag
          git push origin $new_tag
